global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO
  format: json

accessLog:
  format: json

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: firebox_firebox
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@chobani.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
  debug: true
  insecure: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true