#!/bin/bash
# =============================================================================
# Firebox Gateway Port Allocation Summary
# Shows the complete port mapping for all services in the stack
# =============================================================================

echo "🔥 Firebox Gateway Stack - Port Allocation Summary"
echo "=================================================================="
echo ""

echo "🌐 INFRASTRUCTURE SERVICES"
echo "--------------------------"
echo "Service              | Host Port | Container Port | URL"
echo "---------------------|-----------|----------------|--------------------"
echo "Traefik (HTTP)       | 80        | 80             | http://localhost"
echo "Traefik (HTTPS)      | 443       | 443            | https://localhost" 
echo "Traefik (Dashboard)  | 8080      | 8080           | http://localhost:8080"
echo "Backend API          | 5000      | 5000           | http://localhost:5000"
echo "Frontend             | 3000      | 3000           | http://localhost:3000"
echo "Prometheus           | 9090      | 9090           | http://localhost:9090"
echo "Grafana              | 3001      | 3000           | http://localhost:3001"
echo "cAdvisor             | 8081      | 8080           | http://localhost:8081"
echo "Node Exporter        | 9100      | 9100           | http://localhost:9100"
echo "PostgreSQL           | 5432      | 5432           | localhost:5432"
echo ""

echo "🚀 IGNITION GATEWAY SERVICES"
echo "-----------------------------"
echo "Gateway    | IP Address   | HTTP Port | HTTPS Port | GAN Port | URL"
echo "-----------|--------------|-----------|------------|----------|-----------------------------"
echo "VIGVIS     | 10.1.32.71   | 8071      | 8471       | 8671     | http://localhost:8071"
echo "CVSIGDT1   | 10.1.32.51   | 8051      | 8451       | 8651     | http://localhost:8051"
echo "CVSIGDT2   | 10.1.32.52   | 8052      | 8452       | 8652     | http://localhost:8052"
echo "VIGDS3     | 10.1.32.53   | 8053      | 8453       | 8653     | http://localhost:8053"
echo "VIGDS4     | 10.1.32.54   | 8054      | 8454       | 8654     | http://localhost:8054"
echo "VIGDEV     | 10.1.32.70   | 8070      | 8470       | 8670     | http://localhost:8070"
echo "VIGSVC     | 10.1.32.73   | 8073      | 8473       | 8673     | http://localhost:8073"
echo "VIGSVR     | 10.1.32.72   | 8072      | 8472       | 8672     | http://localhost:8072"
echo ""

echo "🔗 GATEWAY CONNECTION TOPOLOGY"
echo "-------------------------------"
echo "Hub Model (VIGVIS connects to all):"
echo "  VIGVIS → CVSIGDT1, CVSIGDT2, VIGDS3, VIGDS4, VIGDEV, VIGSVC"
echo ""
echo "Service Model (connects to VIGVIS):"
echo "  VIGDEV → VIGVIS"
echo "  VIGSVC → VIGVIS"
echo ""
echo "Data Collection (connects to VIGSVC):"
echo "  CVSIGDT1 → VIGSVC"
echo "  CVSIGDT2 → VIGSVC"
echo "  VIGDS3 → VIGSVC"
echo "  VIGDS4 → VIGSVC"
echo ""

echo "📊 PORT ALLOCATION STRATEGY"
echo "---------------------------"
echo "• Infrastructure: 3000-5000, 8080-9100 range"
echo "• Gateways: IP-based allocation (8000 + last IP octet)"
echo "• HTTP: 8000 + octet (e.g., 10.1.32.71 → 8071)"
echo "• HTTPS: 8400 + octet (e.g., 10.1.32.71 → 8471)"
echo "• GAN: 8600 + octet (e.g., 10.1.32.71 → 8671)"
echo "• No port conflicts detected ✅"
echo ""

echo "🐳 DOCKER NETWORKS"
echo "------------------"
echo "• firebox: Main application network"
echo "• monitoring: Prometheus monitoring stack"
echo "• gateway: Ignition gateway network (10.1.32.0/24)"
echo ""

echo "💾 PERSISTENT VOLUMES"
echo "---------------------"
echo "• prometheus_data: Prometheus metrics storage"
echo "• grafana_data: Grafana dashboards and settings"
echo "• postgres_data: Database storage"
echo "• traefik_data: SSL certificates and config"
echo "• vigvis_data, cvsigdt1_data, etc.: Gateway data"
echo "• gateway_backups: Shared backup storage"
echo ""

echo "🎯 QUICK ACCESS COMMANDS"
echo "------------------------"
echo "Start complete stack:     ./gateway-stack.sh start"
echo "Start only gateways:      ./gateway-stack.sh start-gateways"
echo "Check stack status:       ./gateway-stack.sh status"
echo "View gateway logs:        ./gateway-stack.sh logs vigvis"
echo "Restart gateway:          ./gateway-stack.sh restart vigvis"
echo "Test connectivity:        python3 config/test_gateway_config.py"
echo "Port validation:          python3 config/port_manager.py --validate"